debezium/debezium-connector-spanner

- src/main/java/io/debezium/connector/spanner/task/leader/rebalancer/TaskPartitionEqualSharingRebalancer.java
- src/main/java/io/debezium/connector/spanner/task/leader/rebalancer/TaskPartitionGreedyLeaderRebalancer.java
- src/test/java/io/debezium/connector/spanner/schema/KafkaSpannerTableSchemaTest.java
- src/test/java/io/debezium/connector/spanner/task/operation/ChildPartitionOperationTest.java
Depends on https://github.com/debezium/debezium/pull/4183
> DBZ-2439 DBZ-4669 Align with new formatter/checkstyle

- .github/dependabot.yml
- .github/workflows/ci-core.yml
- .github/workflows/ci-docker-image.yml
- .github/workflows/ci-tests.yml
- .github/workflows/contributor-check.yml
- .github/workflows/cross-maven.yml
- .github/workflows/maven.yml
- .github/workflows/octocat-commits-check.yml
- .github/workflows/sanity-check.yml
I haven't push rights for this repo, thus sending a PR.
> CI actions bump

- src/main/java/io/debezium/connector/spanner/SpannerConnectorTask.java
- src/main/java/io/debezium/connector/spanner/config/BaseSpannerConnectorConfig.java
- src/main/java/io/debezium/connector/spanner/processor/SpannerEventDispatcher.java
- src/main/java/io/debezium/connector/spanner/processor/heartbeat/SpannerHeartbeat.java
- src/main/java/io/debezium/connector/spanner/processor/heartbeat/SpannerHeartbeatFactory.java
- src/main/java/io/debezium/connector/spanner/schema/KafkaSpannerTableSchemaFactory.java
- src/test/java/io/debezium/connector/spanner/SpannerStreamingChangeEventSourceTest.java
- src/test/java/io/debezium/connector/spanner/kafka/schema/KafkaSpannerSchemaTest.java
- src/test/java/io/debezium/connector/spanner/processor/SpannerEventDispatcherTest.java
- src/test/java/io/debezium/connector/spanner/processor/heartbeat/SpannerHeartbeatFactoryTest.java
- src/test/java/io/debezium/connector/spanner/processor/heartbeat/SpannerHeartbeatTest.java
- src/test/java/io/debezium/connector/spanner/schema/KafkaSpannerSchemaTest.java
- src/test/java/io/debezium/connector/spanner/schema/KafkaSpannerTableSchemaFactoryTest.java
https://issues.redhat.com/browse/DBZ-5743
> DBZ-5743 Introduce a new unicode topic naming strategy

- pom.xml
- src/main/java/io/debezium/connector/spanner/SpannerConnectorConfig.java
- src/main/java/io/debezium/connector/spanner/config/BaseSpannerConnectorConfig.java
- src/main/java/io/debezium/connector/spanner/config/validation/ChangeStreamValidator.java
- src/main/java/io/debezium/connector/spanner/db/DatabaseClientFactory.java
- src/test/java/io/debezium/connector/spanner/SpannerConnectorTest.java
- src/test/java/io/debezium/connector/spanner/config/BaseSpannerConnectorConfigTest.java
- src/test/java/io/debezium/connector/spanner/config/validation/ConfigurationValidatorTest.java
- src/test/java/io/debezium/connector/spanner/db/DatabaseClientFactoryTest.java
- src/test/java/io/debezium/connector/spanner/db/SpannerChangeStreamFactoryTest.java
Add Database role support for Spanner Connector config.
> DBZ-6192 - Add Database role support for Spanner Connector config.

- src/main/java/io/debezium/connector/spanner/SpannerConnectorTask.java
- src/main/java/io/debezium/connector/spanner/config/validation/ChangeStreamValidator.java
- src/main/java/io/debezium/connector/spanner/db/SpannerChangeStreamFactory.java
- src/main/java/io/debezium/connector/spanner/db/dao/ChangeStreamDao.java
- src/main/java/io/debezium/connector/spanner/db/dao/ChangeStreamResultSet.java
- src/main/java/io/debezium/connector/spanner/db/dao/SchemaDao.java
- src/main/java/io/debezium/connector/spanner/db/mapper/ChangeStreamRecordMapper.java
- src/main/java/io/debezium/connector/spanner/db/model/ChildPartition.java
- src/main/java/io/debezium/connector/spanner/db/model/Mod.java
- src/main/java/io/debezium/connector/spanner/db/model/ModType.java
- src/main/java/io/debezium/connector/spanner/db/model/ValueCaptureType.java
- src/main/java/io/debezium/connector/spanner/db/model/event/ChildPartitionsEvent.java
- src/main/java/io/debezium/connector/spanner/db/model/event/DataChangeEvent.java
- src/main/java/io/debezium/connector/spanner/db/model/event/HeartbeatEvent.java
- src/main/java/io/debezium/connector/spanner/db/model/schema/Column.java
- src/main/java/io/debezium/connector/spanner/db/model/schema/SpannerSchema.java
- src/main/java/io/debezium/connector/spanner/db/stream/SpannerChangeStreamService.java
- src/test/java/io/debezium/connector/spanner/db/SpannerChangeStreamFactoryTest.java
- src/test/java/io/debezium/connector/spanner/db/dao/SchemaDaoTest.java
- src/test/java/io/debezium/connector/spanner/db/mapper/ChangeStreamRecordMapperTest.java
- src/test/java/io/debezium/connector/spanner/db/mapper/TestJsonMapper.java
- src/test/java/io/debezium/connector/spanner/db/metadata/SchemaValidatorTest.java
- src/test/java/io/debezium/connector/spanner/db/model/schema/ColumnTest.java
- src/test/java/io/debezium/connector/spanner/db/stream/SpannerChangeStreamServiceTest.java
Contains changes for supporting Postgres Dialect Spanner in connector.
Bug ID : https://issues.redhat.com/browse/DBZ-6178
> DBZ-6178 Connector changes for Spanner Postgres Dialect 

- src/main/java/io/debezium/connector/spanner/config/validation/ChangeStreamValidator.java
- src/main/java/io/debezium/connector/spanner/db/dao/SchemaDao.java
@nancyxu123 Please LGTM this request for a minor fix and case insensitivity.
@jpechane
> DBZ-6178 Minor fixes and case insetivity for CS name

- pom.xml
- src/main/java/io/debezium/connector/spanner/db/dao/ChangeStreamDao.java
Enable the docker tag to be configurable via -Ddocker.tag.name
> DBZ-6302 Enable the docker tag to be configurable via -Ddocker.tag.name

- src/main/java/io/debezium/connector/spanner/db/dao/SchemaDao.java
- src/main/java/io/debezium/connector/spanner/db/model/schema/SpannerSchema.java
- src/test/java/io/debezium/connector/spanner/db/dao/SchemaDaoTest.java
Use application level join since the issue with same code has been there previously in https://github.com/debezium/debezium-connector-spanner/pull/18. 
https://issues.redhat.com/browse/DBZ-6238
> DBZ-6238 Use application level join rather than DB.

- src/main/java/io/debezium/connector/spanner/config/validation/ChangeStreamValidator.java
- src/main/java/io/debezium/connector/spanner/db/dao/SchemaDao.java
> Minor change for getting the all and all_columns as booleans

- src/main/java/io/debezium/connector/spanner/SpannerChangeEventSourceCoordinator.java
- src/main/java/io/debezium/connector/spanner/SpannerConnectorTask.java
- src/test/java/io/debezium/connector/spanner/SpannerStreamingChangeEventSourceTest.java
https://issues.redhat.com/browse/DBZ-1973
follow https://github.com/debezium/debezium/pull/4515
> DBZ-1973 Add support for Notifications

- src/main/java/io/debezium/connector/spanner/SpannerStreamingChangeEventSource.java
- src/main/java/io/debezium/connector/spanner/processor/SpannerChangeRecordEmitter.java
- src/test/java/io/debezium/connector/spanner/processor/SpannerChangeRecordEmitterTest.java
* Change signature of ChangeEventEmitter
Addresses/Closes DBZ-6366
> DBZ-6366: Code Improvements for skip.messages.without.change

- src/main/java/io/debezium/connector/spanner/SpannerChangeEventSourceFactory.java
- src/test/java/io/debezium/connector/spanner/SpannerChangeEventSourceFactoryTest.java
refer to: https://github.com/debezium/debezium/pull/4614
> DBZ-6416 Add support for Notifications

- pom.xml
https://issues.redhat.com/browse/DBZ-6649
> DBZ-6649 Upgrade gRPC to 1.56.1

- src/main/java/io/debezium/connector/spanner/context/source/SpannerSourceTaskContext.java
- src/main/java/io/debezium/connector/spanner/metrics/jmx/SpannerStreamingChangeEventSourceMetrics.java
https://issues.redhat.com/browse/DBZ-6603
> DBZ-6603 Support for custom tags in the connector metrics

- src/main/java/io/debezium/connector/spanner/SpannerStreamingChangeEventSource.java
- src/main/java/io/debezium/connector/spanner/context/offset/PartitionOffset.java
- src/main/java/io/debezium/connector/spanner/context/offset/SpannerOffsetContextFactory.java
- src/main/java/io/debezium/connector/spanner/processor/heartbeat/SpannerHeartbeat.java
- src/main/java/io/debezium/connector/spanner/task/SynchronizationTaskContext.java
- src/main/java/io/debezium/connector/spanner/task/TaskStateChangeEventHandler.java
- src/main/java/io/debezium/connector/spanner/task/operation/RemoveFinishedPartitionOperation.java
- src/test/java/io/debezium/connector/spanner/processor/heartbeat/SpannerHeartbeatTest.java
Send tombstone events after partition queries are finished
> DBZ-6658 Send tombstone events after partition queries are finished

- src/main/java/io/debezium/connector/spanner/SpannerChangeEventSourceFactory.java
related to: https://github.com/debezium/debezium/pull/4741
> DBZ-6731 Adapting to SnapshotChangeEventSource changes

- src/main/java/io/debezium/connector/spanner/task/operation/ClearSharedPartitionOperation.java
Clear shared token if token is owned by any of the tasks
> DBZ-6458 Clear shared token if token is owned by any of the tasks

- src/main/java/io/debezium/connector/spanner/SpannerConnectorTask.java
https://issues.redhat.com/browse/DBZ-4321
Sibling main repository PR https://github.com/debezium/debezium/pull/5081
> DBZ-4321 Add `PostProcessor` support

- src/main/java/io/debezium/connector/spanner/SpannerChangeEventSourceCoordinator.java
- src/main/java/io/debezium/connector/spanner/SpannerConnectorTask.java
- src/test/java/io/debezium/connector/spanner/SpannerStreamingChangeEventSourceTest.java
Related to https://github.com/debezium/debezium/pull/5196
> DBZ-7301 Inject the SnapshotterService

- src/test/java/io/debezium/connector/spanner/SpannerConnectorConfigTest.java
- src/test/java/io/debezium/connector/spanner/SpannerSourceInfoStructMakerTest.java
- src/test/java/io/debezium/connector/spanner/kafka/schema/KafkaSpannerSchemaTest.java
https://issues.redhat.com/browse/DBZ-7107
Requires - https://github.com/debezium/debezium/pull/5261
> DBZ-7107 Add micro/nano second based timestamps to source info block

- src/main/java/io/debezium/connector/spanner/SpannerConnectorConfig.java
- src/main/java/io/debezium/connector/spanner/SpannerConnectorTask.java
related to: https://github.com/debezium/debezium/pull/5401
> DBZ-7308 Adapt to core changes

- src/main/java/io/debezium/connector/spanner/context/source/SpannerSourceTaskContext.java
relates to: https://github.com/debezium/debezium/pull/5718
> DBZ-8035 Align core changes

- src/main/java/io/debezium/connector/spanner/context/offset/SpannerOffsetContext.java
related to: https://github.com/debezium/debezium/pull/5938 that must be merged first
> DBZ-7903 Align core changes

- src/test/java/io/debezium/connector/spanner/SpannerConnectorConfigTest.java
- src/test/java/io/debezium/connector/spanner/SpannerSourceInfoStructMakerTest.java
Depends on https://github.com/debezium/debezium/pull/6037
> DBZ-8499 Make source info versioned

- src/test/java/io/debezium/connector/spanner/GracefulRestartIT.java
Offset is correctly updated now and we receive just update after restart.
https://issues.redhat.com/browse/DBZ-8947
> DBZ-8947 Correct the test

- src/main/java/io/debezium/connector/spanner/SpannerConnectorTask.java
- src/main/java/io/debezium/connector/spanner/metrics/jmx/SpannerStreamingChangeEventSourceMetrics.java
- src/main/java/io/debezium/connector/spanner/processor/SpannerEventDispatcher.java
- src/test/java/io/debezium/connector/spanner/SpannerStreamingChangeEventSourceTest.java
- src/test/java/io/debezium/connector/spanner/processor/SpannerEventDispatcherTest.java
related to: https://github.com/debezium/debezium/pull/6430
> DBZ-9020 Align to core changes

- pom.xml
- src/main/java/io/debezium/connector/spanner/SpannerConnector.java
requires: https://github.com/debezium/debezium/pull/6496
> DBZ-9110 Align core changes
